### ISSUE TITLE
static serving from resources after assembly fails

### ISSUE THREAD

**Issue by siddhartha-gadgil** [lihaoyi/cask#4]
In https://github.com/siddhartha-gadgil/MillScalaServer (and also a larger project, which is what I wanted), serving from resources works fine with `server.run` and `server.runBackground`but fails on running the result of `server.assembly`

* Even files in the `resources` folder behave the same way.

**Comment by siddhartha-gadgil** [comment]
In the following code in cask, `relPath` is defined but not used.
```
val relPath = java.nio.file.Paths.get(path)
    val (data0, statusCode0) = resourceRoot.getResourceAsStream(path) match{
      case null => ("": Response.Data, 404)
      case res => (res: Response.Data, 200)
    }
```

is that a typo (which accidentally does not matter in `run`)?

**Comment by siddhartha-gadgil** [comment]
I had tried "" (empty) which failed and "." worked. I'll see what happens
if I move my resources.

**Comment by lihaoyi** [comment]
might be fixed in https://github.com/lihaoyi/cask/commit/4369a2f3af843a45bd0f29c58eb0c69158f4c87e

**Comment by siddhartha-gadgil** [comment]
Is there a way to refer to this in mill?

**Comment by siddhartha-gadgil** [comment]
Fixed in the toy project. Thanks a lot.
I'll confirm in the larger project and close

**Comment by siddhartha-gadgil** [comment]
It is indeed fixed. Thanks again.

**Comment by efim** [comment]
For anyone who gets here with similar problem:

I had errors 404 with server not being able to locate images by path that should have worked
that turned out to be a problem with browser - it was caching 404 from builds that were incorrect
i've been able troubleshoot that by not trusting initial 404 responses, and manually triggering "Resend" in the Network console

Overall the function works as should be expected
'src/main/resources' is root, and for example to server 'src/main/resources/public' the method should return "public"
